export const MESSAGE_TYPES = {
  ADD_EVENTS: "ADD_EVENTS",
  DELETE_CALENDAR: "DELETE_CALENDAR",
  QUESTION_READY: "QUESTION_READY",
  MAKE_IDLE: "MAKE_IDLE",  //see if it can be removed
  GET_API_STATE: "GET_API_STATE"
};